name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: '20.10.0'

        # TODO: docker

      - name: Build project
        run: npm run build --prod
